version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    volumes:
      - db_data:/app/data
    restart: unless-stopped

volumes:
  db_data:
